plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mountaintorq.kccassessment'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mountaintorq.kccassessment'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0-test'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.test'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
